# Generated by Django 3.0.8 on 2020-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='protfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('project_link', models.URLField(blank=True, db_index=True, max_length=100)),
                ('project_image', models.ImageField(blank=True, upload_to='media/images')),
                ('project_type', models.CharField(choices=[('mobile', 'mobile'), ('development', 'development'), ('design', 'design')], max_length=100)),
            ],
        ),
    ]
