# Generated by Django 3.0.8 on 2021-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_myarea_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myarea',
            name='icon',
        ),
        migrations.AddField(
            model_name='myarea',
            name='fa_fa_awsome_icon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
