# Generated by Django 3.0.8 on 2021-01-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210111_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='backround_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='myarea',
            name='fa_fa_awsome_icon',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
